### ISSUE TITLE
Error updating faq

### ISSUE THREAD

**Issue by simonstearn1** [zouchaoqun/ezfaq#7]
We have revision 3824 of redmine installed (latest dev 1.0 as I write) on fedora 13 with mysql.  We have 0.3.5 of ezfaq installed.  This worked fine with 0.9.2 of redmine, but since upgrading we see the following error in the production log file when updating an existing faq:

Processing EzfaqController#edit (for 192.168.2.82 at 2010-07-01 14:15:56) [POST]
  Parameters: {"faq"=>{"related_message_id"=>"", "answer"=>"Test Update", "related_version_id"=>"", "version"=>"1", "category_id"=>"", "question"=>"Pass the Multiple Values at a time in Query Expression", "is_valid"=>"true", "due_date"=>"", "assigned_to_id"=>"", "difficulty"=>"5", "related_issue_id"=>""}, "commit"=>"Update", "action"=>"edit", "faq_id"=>"23", "authenticity_token"=>"ds/2SRiKkzB9xeNDfGFoX+E3/Ug0trRg8eJvd2mwWuM=", "id"=>"saturn-help", "controller"=>"ezfaq", "difficulty_label"=>"Difficulty", "attachments"=>{"1"=>{"description"=>""}}}

NoMethodError (undefined method `attach_files' for #<EzfaqController:0xb61df5f4>):
  vendor/plugins/ezfaq_plugin/app/controllers/ezfaq_controller.rb:99:in`edit'
  thin (1.2.7) lib/thin/connection.rb:76:in `pre_process'
  thin (1.2.7) lib/thin/connection.rb:74:in`catch'
  thin (1.2.7) lib/thin/connection.rb:74:in `pre_process'
  thin (1.2.7) lib/thin/connection.rb:57:in`process'
  thin (1.2.7) lib/thin/connection.rb:42:in `receive_data'
  eventmachine (0.12.10) lib/eventmachine.rb:256:in`run_machine'
  eventmachine (0.12.10) lib/eventmachine.rb:256:in `run'
  thin (1.2.7) lib/thin/backends/base.rb:57:in`start'
  thin (1.2.7) lib/thin/server.rb:156:in `start'
  thin (1.2.7) lib/thin/controllers/controller.rb:80:in`start'
  thin (1.2.7) lib/thin/runner.rb:177:in `send'
  thin (1.2.7) lib/thin/runner.rb:177:in`run_command'
  thin (1.2.7) lib/thin/runner.rb:143:in `run!'
  thin (1.2.7) bin/thin:6
  /usr/bin/thin:19:in`load'
  /usr/bin/thin:19

Rendering /home/redmine/Applications/redmine-1.0.beta1/public/500.html (500 Internal Server Error)

**Comment by hukarere** [comment]
I solved the same issue by replacing:
  attach_files
with:
  Attachment.attach_files
in:
  ezfaq_plugin/app/controllers/ezfaq_controller.rb
